### ISSUE TITLE
Add ability to set path to bin directory

### ISSUE THREAD

**Issue by bveina** [tlgkccampbell/code-ca65#14]
out of the box CL65 must be included in path. it would be easier to setup if the path could be added in ```cl65.config.json``` and then prepended to the cl65 cli call.
```
{
    "path": "u:\\CC65\\bin\\",
    "input": "blink.asm",
    "params": "--verbose"
}
```

as a current workaround ive modified line 64 of extension.js as follows
``` let cli = `${cl65Config.path} "${fileName}" `;```

**Comment by tlgkccampbell** [comment]
I've just pushed 1.2.3 to the Marketplace, which allows you to do this by adding a parameter to `cl65config.json` called `executable` that contains the full path to the `cl65` executable file.
